### PR TITLE
Contrail kilo

### PR DESCRIPTION
**Pull request by pupapaik**
compatibility fixes for Kilo https://bugs.launchpad.net/juniperopenstack/+bug/1483232

### CODE REVIEW

**Comment by moghea** [comment]
what is a need to put a juno specific changes in master branch? We have release specific branches for this particular repo, where as specific optilimization is handled for that particular release. If these are needed for kilo, then it has to go in kilo branch..which is not created yet.

**Comment by pupapaik** [comment]
OK, then create a new branch contrail_kilo and I can do pull request with following fix https://github.com/pupapaik/contrail-nova-extensions/commit/728cc2fcb712723125d4dc6b23017330adf5e2c7 come from contrail_juno.

**Comment by moghea** [comment]
which nova-api are you using? if package is not 2015.1 then provisioning will set api wrongly to contrail_nova_extension.

**Comment by pupapaik** [comment]
I have nova-api 1:2015.1.0-0ubuntu1.1~cloud0

**Comment by pupapaik** [comment]
Please create branch contrail_kilo.

**Comment by moghea** [comment]
contrail_kilo branch is created..

**Comment by pupapaik** [comment]
OK, I will do pull request into contrail_kilo.

**Pull request closed without merging**
